version: '3.8'
services:
  app:
    image: appscrip007/react-le-offers-v2
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/src
        - /src/node_modules
        - /src/.next
    ports:
      - "3000:3000"